Generate HiWiFi EEPROM

diff --git a/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom b/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
--- a/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
+++ b/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
@@ -21,6 +21,38 @@ rt2x00_eeprom_extract() {
 		rt2x00_eeprom_die "failed to extract from $mtd"
 }
 
+hiwifi_eeprom_extract() {
+	local part=$1
+	local offset=$2
+	local mac_addr=$3
+	local mtd
+
+	. /lib/functions.sh
+
+	mtd=$(find_mtd_part $part)
+	[ -n "$mtd" ] || exit 1
+	dd if=$mtd of=/lib/firmware/$FIRMWARE bs=1 skip=$offset count=4
+	macaddr_2bin $mac_addr >> /lib/firmware/$FIRMWARE
+	dd if=$mtd bs=1 skip=$(echo $offset | awk '{print $1+10}') count=502 >> /lib/firmware/$FIRMWARE
+}
+
+hiwifi_get_mac()
+{
+	local part
+	local mac_dirty
+
+	part=$(find_mtd_part "bdinfo")
+	if [ -z "$part" ]; then
+		echo "hiwifi_get_mac: partition $mtdname not found!" >&2
+		return
+	fi
+
+	mac_dirty=$(strings "$part" | sed -n 's/^'"Vfac_mac "'=//p')
+
+	# "canonicalize" mac
+	[ -n "$mac_dirty" ] && macaddr_canonicalize "$mac_dirty"
+}
+
 FW="/lib/firmware/$FIRMWARE"
 [ -e "$FW" ] && exit 0
 
@@ -36,7 +68,12 @@ case "$FIRMWARE" in
 		;;
 	esac
 	;;
-
+"hiwifi_wlan24_caldata.eeprom")
+	case $board in
+	hiwifi-hc5761)
+		hiwifi_eeprom_extract "factory" 0 $(hiwifi_get_mac)
+		;;
+	esac
 "rt2x00pci_1_0.eeprom")
 	case $board in
 	cy-swr1100)
